# Site settings
title: blindr
email: marc.antoine.hinse@gmail.com
url: https://example.github.io
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
favIconPath: "img/favicon.png"
previewPath: "img/nexus.png"

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 0097fd #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Marc-Antoine Hinse
  social: Around the Tubes

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/tymarc1
  - title: facebook
    url: https://www.facebook.com/mhinse
  - title: github
    url: https://github.com/TyMarc/blindr


# Build settings
markdown: kramdown
permalink: pretty
