# Site settings
title: blindr
email: your-email@domain.com
url: https://example.github.io
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 0097fd #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: DCIÉTS
  location: 1100 Rue Notre-Dame Ouest, Montréal, QC H3C 1K3, Canada
  social: Around the Tubes
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/dciets
  - title: facebook
    url: https://www.facebook.com/dciets
  - title: github
    url: https://github.com/ldionmarcil/blindr

# Postal address (add as many lines as necessary)
address:
  - line: 1100 Rue Notre-Dame Ouest
  - line: Montréal, QC

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
